spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:3307/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret= secret123for%$#^%&$this><:2app-=098first_432923jfdsf1+test
spring.jwt.expiration=900000

